FROM nvidia/opencl:runtime-ubuntu18.04

WORKDIR /katago-opencl
ADD ./analysis-k80.cfg /katago-opencl
ADD ./katago-tuning /root/.katago

RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    libzip-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN wget -nv https://github.com/lightvector/KataGo/releases/download/v1.3.5/katago-v1.3.5-opencl-linux-x64.zip -O katago-release.zip \
  && wget -nv https://github.com/lightvector/KataGo/releases/download/v1.3.4/g170-b30c320x2-s2271129088-d716970897.bin.gz -O ktnetwork.bin.gz \
  && unzip katago-release.zip \
  && rm -f katago-release.zip \
  && chmod a+x katago

CMD ./katago gtp -config analysis-k80.cfg -model ./ktnetwork.bin.gz
